#pragma once
enum GAME_STEP { STEP_MENU, STEP_SOLO_PLAY, STEP_SOLO_RESULT, STEP_EXIT };

enum COLOR { DARK_BLUE = 1,	DARK_GREEN,	DARK_SKY, DARK_RED,	DARK_PURPLE, DARK_YELLOW, DARK_WHITE, 
			GRAY, BLUE, GREEN, SKY, RED, PURPLE, YELLOW, WHITE };